# cover      fill screen, cropping if necessary
# contain    show entire image, possibly leaving empty space
# fill       stretch image to fill the screen
# tile       repeat the image

#    path = /usr/share/hypr/wall0.png

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/arch-linux-one.jpeg
    fit_mode = cover
}

splash = false